In [3]:
'''
Array and Matrix are key features of Numpy.
Numpy was not part of python packages initially.
Numpy has been borrowed from Matlab.
'''
import numpy as np
from numpy.random import randint as ri

In [4]:
#create a numpy Array from a LIST
mylist = [1,2,3]
print (np.array( mylist))
print ('type is ND Array ', type(np.array(mylist)) )


[1 2 3]
type is ND Array  <class 'numpy.ndarray'>


In [11]:
#Upcasting - if you pass a LIST as input with values of different data type, numpy upcasts all values to higher data types

mylist = [1,2,3.0]
print (np.array( mylist))


mylist = [1,2,3.0, "Hi"]
print (np.array( mylist))

#create array while specifying data type using dtype command.
mylist = [1,2,3.0]
print (np.array( mylist , dtype = str))

[1. 2. 3.]
['1' '2' '3.0' 'Hi']
['1' '2' '3.0']


In [6]:
#creating multi-dimension array

#below creates a 2x2 array as we gave list of list as input
print (np.array([[1, 2], [3, 4]]) )

print ("-------------")

# Minimum dimensions 2: use of ndmin option
# ndmin specifies the minimum dimensions of resultant array. so if value = 5 then 5 array one inside the other, are formed.
print (np.array([1, 2, 3], ndmin=5))

print ("-------------")
#print shape of array using 'shape' command
a = np.array([[1, 2], [3, 4]]) 
print ('numpy array "a"  has shape ', a.shape)

[[1 2]
 [3 4]]
-------------
[[[[[1 2 3]]]]]
-------------
numpy array "a"  has shape  (2, 2)


In [24]:
#creating Complex Array

#here imaginary number is missing and set as 0
print (np.array([1,2,3,4],dtype=complex))

# do : 24-27 min
'''

Below complex = a + ib
we define data type of a and b separately. 
If we dont, and instead pass type=complex, then by default the values are of 64 bit.

Here i4 = integer of 8x4 = 32 bit
similarly, we can have 
    f4 = float of 32 bit
    i8 = integer of 64 bit
    

'''
x = np.array([(1,2), (3,4)], dtype=[('a','<i4'), ('b','<f8') ])
print (x)
print ('real values ', x['a'])
print ('imaginary values ', x['b'])

print (x[0])
print (x[1])
print (x[0][0], type(x[0][0]))
print (x[0][1], type(x[0][1]))
print (x[1][0], type(x[1][0]))
print (x[1][1], type(x[1][1]))



[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
[(1, 2.) (3, 4.)]
real values  [1 3]
imaginary values  [2. 4.]
(1, 2.)
(3, 4.)
1 <class 'numpy.int32'>
2.0 <class 'numpy.float64'>
3 <class 'numpy.int32'>
4.0 <class 'numpy.float64'>


In [28]:
#matrix creation 2 ways
'''

Numpy supports 2 type of data type - array and matrix
Matrix is a sub class of array.


'''
# method 1: Creating an array from sub-classes:
matrix = np.mat(np.array([[1, 2],[4,7]]))
print (matrix, type(matrix))


#method 2: from string of integers, with each row of matrix separated by semi-colon - ";"
print (np.mat('1 2; 3 4'))

[[1 2]
 [4 7]] <class 'numpy.matrix'>
[[1 2]
 [3 4]]


## numpy.asarray()

In [29]:
# asarray() function - to create array. Same as np.array()
# asarray() also used to convert data into an N-Dimension array.

#input - list
a = [1, 2]
print (np.asarray(a), type(np.asarray(a)))

#input - tuples
a=(1,2)
print (np.asarray(a), type(np.asarray(a)))

[1 2] <class 'numpy.ndarray'>
[1 2] <class 'numpy.ndarray'>


## numpy.asanyarray()

numpy.array() is SAME as numpy.asarray()

But in case of numpy.asanyarray() --> 
It also returns an array, but if input is kind of array (i.e. matrix), it doesnt do conversion and returns as it is.
This is unlike np.asarray() that converts matrix into array.



In [35]:
a = np.matrix([[1, 2]])
print (a)

print ('asanyarray')
print (np.asanyarray(a), type(np.asanyarray(a)))
print (np.asanyarray(a) is a)

print ('asarray')
print (np.asarray(a),type(np.asarray(a)))
print (np.asarray(a) is a)


[[1 2]]
asanyarray
[[1 2]] <class 'numpy.matrix'>
True
asarray
[[1 2]] <class 'numpy.ndarray'>
False


## Deep and Shallow Copy : numpy.copy


Shallow Copy: here 2 array objects are referig to same array location.
So, change in 1 is reflected in Other.

Deep Copy: we create a new copy of one array in a separate memory location.
So, change in 1 is NOT reflected in Other.

In [44]:
print ('Shallow Copy')
a = np.array([1, 2])
b = a   #shallow copy

print ('a ', a)
print ("b ", b)

print ('after change')

b[0]=100

print ("b ", b)
print ("a ", a)


Shallow Copy
a  [1 2]
b  [1 2]
after change
b  [100   2]
a  [100   2]


In [43]:
print ('Deep Copy:')
a = np.array([1, 2])

c= np.array(a, copy=True) 
print ('a ', a)
print ('c ',c)

a[0] = 5
print ('after change')
print ('a ', a)
print ('c ',c)



Deep Copy:
a  [1 2]
c  [1 2]
after change
a  [5 2]
c  [1 2]


# numpy.fromfunction

Construct an array by executing a function over each Coordinate.

Syntax -
np.fromfunction( func, shape of array, **kwargs)

for example in below we give shape as (3,3) which is a 3x3 matrix and function is applied to all indices in combination.


In [45]:
np.fromfunction( lambda i,j: i==j, (3,3), dtype=int )

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [46]:
np.fromfunction( lambda i,j: i+j, (3,3), dtype=int )

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## numpy.fromiter  create array from iterable object

It takes an iterable object as input and converts it into Numpy Array.


In [57]:
iterable = (x for x in range(10))
np.fromiter(iterable, dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#other way of creating above array
np.array(range(10),int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
iterable = (x*x for x in range(10))
np.fromiter(iterable, dtype=float)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

## numpy.fromstring()   create array from a string

In [59]:
np.fromstring('1 2 3 4', sep=' ',dtype=int)

array([1, 2, 3, 4])

In [61]:
np.fromstring('1, 2, 3, 4', sep=', ',dtype=int)

array([1, 2, 3, 4])

## ndim, ndmin, shape and size

ndmin = array dimension set at time of creation of array
ndim = returns dimension of array - how may dimenion array we have like 2-d, 3-d, 4-d etc
shape = returns shape of array
size = returns number of elements in array



In [78]:
my_mat = [[1,2,3,100,200],[4,5,6,300,400],[7,8,9,500,600]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim) #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size) #size gives the total number of elements
print("Shape of this matrix: ", mat.shape) #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype) #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[  1   2   3 100 200]
 [  4   5   6 300 400]
 [  7   8   9 500 600]] 
----------
Dimension of this matrix:  2
Size of this matrix:  15
Shape of this matrix:  (3, 5)
Data type of this matrix:  int64


## Note - input element to np.array() should be of same length - i.e. same number of elements in each input list.
## otherwise numpy treats them as array of list and not integers

For example -


In [79]:
my_mat = [[1,2,3,100,200,700],[4,5,6,300,400],[7,8,9,500,600]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim) #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size) #size gives the total number of elements
print("Shape of this matrix: ", mat.shape) #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype) #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [list([1, 2, 3, 100, 200, 700]) list([4, 5, 6, 300, 400])
 list([7, 8, 9, 500, 600])] 
----------
Dimension of this matrix:  1
Size of this matrix:  3
Shape of this matrix:  (3,)
Data type of this matrix:  object


## arange() vs range()

### range() - 

Python function which takes upto 3 arguments - start, end ,step. In this case, step = INTEGER.

Returns = iterable Object

### arange() - 

Numpy function which takes upto 3 arguments - start, end, step. In this case, step can be FLOAT/INTEGER.

Returns = numpy Array

In [80]:
np.arange(10.5)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [81]:
np.arange(5.5, 6.7, 0.2)

array([5.5, 5.7, 5.9, 6.1, 6.3, 6.5, 6.7])

## linspace()

It creates an Array of equally spaced values.
Takes input - start, end , num of elements including start and step.

In [82]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [110]:
np.linspace(1,10,12)

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [115]:
#by default it includes end point value while generating sequence.
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [114]:
#ignore endpoint value while generating sequence
np.linspace(2.0, 3.0, num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [116]:
#if you want to PRINT the size of step taken, that can also be returned using retstep option.
np.linspace(2.0, 3.0, num=5,endpoint=False, retstep = True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

### logspace

Similar to linspace()

In logspace() we return logarithmic value of input.

Default base=10.

np.logspace(start, stop, num=, endpoint=True,base=10,dtype=None)

In [121]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

## Matrix Creation

Can be done using different methods

np.zeros() - creates a matrix with all values 0s.

np.ones() - creates a matrix with all values 1s.

np.empty() -- creates an empty matrix with random values

np.eye() - creates an Identity Matrix. 
Identity Matrix is a -
1. Square matrix.
2. has all elements along One Diagonal as 1.

These are from posn (0,0), (1,1) to (n-1,n-1) in case of an N-Dimensional Matrix


In [90]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))
print ("--------------------")
print ("--------------------")
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]
--------------------
--------------------
Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [94]:
print("Vector of ones\n---------------------")
print(np.ones(5))
print ("--------------------")
print ("--------------------")
print(np.ones((4,2,3))) # Note matrix dimension specified by Tuples


Vector of ones
---------------------
[1. 1. 1. 1. 1.]
--------------------
--------------------
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [96]:
print("Matrix of 5s by multiplying each element by 5 as shown below \n---------------------")

print(5*np.ones((3,5)))

Matrix of 5s by multiplying each element by 5 as shown below 
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [108]:
print("Empty matrix. np.empty() -- creates an empty matrix with random values\n-------------\n", np.empty((3,5)))

Empty matrix. np.empty() -- creates an empty matrix with random values
-------------
 [[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [109]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print ('''
Identity Matrix is a -
1. Square matrix.
2. has all elements along One Diagonal as 1.
These are from posn (0,0), (1,1) to (n-1,n-1) in case of an N-Dimensional Matrix
''')
print(mat1)

Identity matrix of dimension (4, 4)

Identity Matrix is a -
1. Square matrix.
2. has all elements along One Diagonal as 1.
These are from posn (0,0), (1,1) to (n-1,n-1) in case of an N-Dimensional Matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### reshape

In [122]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
#below gives ERROR as Number of elements in array(=9) is less than dimension of array (3x4=12)
np.arange(9).reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [127]:
#to enable self determination of shape of array, pass at least one value in shape as +ve, and other as any random -ve value.
np.arange(9).reshape(3,-10)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
np.arange(9).reshape(-10,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [131]:
np.arange(9).reshape(-10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [132]:
np.arange(9).reshape(-10,2)   #throws error as num of elements cannot be a multiple of '2'

ValueError: cannot reshape array of size 9 into shape (2)

### diag and diagflat


diag - 
  
   Extract Diagonal elements from MATRIX.
   
   Creates 2-D MATRIX from 1D  Array.

Note - in case of np.diag() --> 'k' represents axis along which diagonal elements are to be picked.

diagflat - input given as list of list/tuple etc. convert to 2D Matrix with elements of list as diagonal element of matrix.


In [6]:
x = np.arange(1,10,1).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.diag(x)

array([1, 5, 9])

In [10]:
'''
In case of np.diag() --> 'k' represents axis along which diagonal elements are to be picked.

 k  0  1  2
 0 [1  2  3]
-1 [4  5  6]
-2 [7  8  9]


k = 0 --> 1, 5, 9
k = 1 --> 2, 6
k = 2 --> 3
k = -1 -> 4, 8
k = -2 -> 7

'''

print (np.diag(x, k=-2))
print (np.diag(x, k=-1))
print (np.diag(x, k=0))
print (np.diag(x, k=1))
print (np.diag(x, k=2))

[7]
[4 8]
[1 5 9]
[2 6]
[3]


In [8]:
y = np.diag(x)
np.diag(y)

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [14]:
nested_list = [[1,2],[3,4]]
np.diagflat(nested_list)


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [15]:
#using different axis by setting 'k'.
np.diagflat(nested_list,k=1)


array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

### triangular matrices: 

np.tri() -An array with ones at and below the given diagonal and zeros elsewhere.

np.tril() = lower triangular matrix - return a Lower triangle of an array.

np.triu() - upper triangular matrix - return a upper triangle of an array.

In [16]:
np.tri(3, 5, k=1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [17]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [18]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], k=0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [19]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], k=1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.triu([[1,2,3],[4,5,6],[7,8,9]], k=0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [21]:
np.triu([[1,2,3],[4,5,6],[7,8,9]], k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [ ]:
1.36

# Random number generation

np.random.rand()  - Random number generation (from Uniform distribution)

np.random.randn() - Numbers from Normal distribution with mean=0 and standard deviation 1 i.e. standard normal

np.random.randint() - Random integer vector. randint (low, high, # of samples to be drawn)

In [3]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.63086318 0.67835049 0.23914044]
 [0.63403824 0.15183432 0.23805608]]


In [4]:
print("Numbers from Normal distribution with  mean = 0 and standard deviation = 1 i.e. standard normal")
print('''
In normal distribution, mean and standard deviation can be anything.
But in case of STANDARD normal distribution, mean = 0 and standard deviation = 1.

''')
print(np.random.randn(4,3))

Numbers from Normal distribution with  mean = 0 and standard deviation = 1 i.e. standard normal

In normal distribution, mean and standard deviation can be anything.
But in case of STANDARD normal distribution, mean = 0 and standard deviation = 1.


[[ 0.0209765  -1.60189352 -0.89518584]
 [ 0.44106771  2.51650308 -0.39156907]
 [ 2.042135    0.10860212 -0.38330018]
 [-0.05886579  0.17627089 -1.45630913]]


In [4]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix.\nNote in above we didnt mention number of samples to be drawn, and so by deafult picked only 1 value.")


Random integer vector: 2

Random integer matrix.
Note in above we didnt mention number of samples to be drawn, and so by deafult picked only 1 value.


In [6]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)


[[82 87 19 88]
 [96 69  6 41]
 [78 92 50 75]
 [66 92 36 69]]


In [7]:
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw


20 samples drawn from a dice throw: [6 3 4 4 1 6 3 1 6 3 6 6 1 4 5 2 2 5 4 4]


### Reshape

In [9]:
from numpy.random import randint as ri

In [5]:
np.random.randint(1,100,9).reshape(3,3)

array([[96, 92, 79],
       [55, 81, 81],
       [71, 86, 25]])

In [6]:
np.random.randint(1,100,(3,3))

array([[37, 84,  2],
       [11, 61, 63],
       [48,  7,  5]])

In [7]:
np.random.randint(1,100,30).reshape(2,3,5)  #2x3x5 matrix

array([[[34, 29, 98, 73, 67],
        [ 2, 11, 32, 85, 21],
        [68, 56, 75, 39, 94]],

       [[71, 12, 68,  2, 17],
        [46, 56, 31, 95, 85],
        [16, 66, 39, 95, 90]]])

In [8]:
a = np.random.randint(1,100,30).reshape(2,3,5)
print ('shape of matrix "a" is ',a.shape)

shape of matrix "a" is  (2, 3, 5)


## Sorting of vectors

np.sort(df, kind=?, axis=?)

kind - default = quicksort; other option - mergesort, heapsort,stable (stable sort)

axis - axis = 0 --> sort along row ; 
       axis = 1 --> sort along column 


In [10]:
from numpy.random import randint as ri

In [12]:
A = ri(1,100, 10)
print("\nVector of random integers\n",'-'*50,"\n",A)


Vector of random integers
 -------------------------------------------------- 
 [67 90 33 88 16 15 14 17 21 60]


In [14]:
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Here is the sorted vector
 -------------------------------------------------- 
 [14 15 16 17 21 33 60 67 88 90]


In [16]:
print ('5x5 matrix of random integers')
A = ri(1,100,(5,5))
A

5x5 matrix of random integers


array([[77, 18, 69, 19, 87],
       [18, 65, 98, 10, 44],
       [ 1, 55,  4, 26, 18],
       [25, 91, 93, 17, 65],
       [83, 88,  2, 61, 65]])

In [22]:
print ('''Sort along Row : axis=0. That is in a column, sort along rows.
Here X-coordinates of values are changing.
Y-coordinates are intact.''')
np.sort(A,axis=0)

Sort along Row : axis=0. That is in a column, sort along rows.
Here X-coordinates of values are changing.
Y-coordinates are intact.


array([[ 1, 18,  2, 10, 18],
       [18, 55,  4, 17, 44],
       [25, 65, 69, 19, 65],
       [77, 88, 93, 26, 65],
       [83, 91, 98, 61, 87]])

In [21]:
print ('''Sort along Column : axis=1. That is, in a row, sort along column.
Here Y-coordinates of values are changing.
X-coordinates are intact.''')
np.sort(A,axis=1)

Sort along Column : axis=1. That is, in a row, sort along column.
Here Y-coordinates of values are changing.
X-coordinates are intact.


array([[18, 19, 69, 77, 87],
       [10, 18, 44, 65, 98],
       [ 1,  4, 18, 26, 55],
       [17, 25, 65, 91, 93],
       [ 2, 61, 65, 83, 88]])

### Max and argmax

max() -- returns max value.

argmax(0 -- returns position of max value.

In [24]:
A = np.random.randint(1,100,20)
A

array([60, 44, 63, 15, 82, 83, 41, 51, 27, 80, 93, 80, 32, 90, 85, 38, 96,
       18, 13, 26])

In [25]:
A.max()

96

In [26]:
A.argmax()

16

### Indexing and Slicing - same as that in python LIST

In [2]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
print("Elements from last backwards are:", arr[-1:7:-1])

Elements from last backwards are: [10  9  8]


In [4]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

Matrix of random 2-digit numbers
--------------------------------
 [[18 73 62 83 11]
 [51 95 51 30 69]
 [35 56 95 54 75]]


In [5]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[73 83]
 [95 30]]


In [6]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[30 69]
 [54 75]]


In [13]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)

mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)

print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)

print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


print ('-----------other way of creating sliced matrix : np.array() command-----')
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)

mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)

print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)

print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix
[[1000   12]
 [  21   22]]

But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]
-----------other way of creating sliced matrix : np.array() command-----

Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix
[[1000   12]
 [  21   22]]

But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Subsetting

In [8]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


Matrix of random 2-digit numbers
--------------------------------
 [[45 13 34 13 46]
 [23 46 94 36 13]
 [11 72 98 47 85]]


In [9]:
mat>50

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True,  True, False,  True]])

In [10]:
mat[mat>50]

array([94, 72, 98, 85])

### Universal Functions: ADD, Subtract, Multiply, Divide.
    
They occur element wise.

In [4]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[2 1 3]
 [9 5 5]
 [7 2 6]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[4 1 9]
 [7 8 5]
 [2 6 8]]


In [16]:
print ('element wise multiplication using "*" operator: A*B ')
mat1*mat2

element wise multiplication using "*" operator: A*B 


array([[24, 56, 40],
       [ 5,  6, 56],
       [28, 20, 12]])

In [18]:
print ('''
Matrix multiplication using "@" operator: A@B 
For 2 matrices to be able to multiple: no. of Col in A = no. of Rows in B.
i.e. their dimensions should be : A (n x m) and B (m x z) --> resultant will have dimension n x z

''')
mat1@mat2


Matrix multiplication using "@" operator: A@B 
For 2 matrices to be able to multiple: no. of Col in A = no. of Rows in B.
i.e. their dimensions should be : A (n x m) and B (m x z) --> resultant will have dimension n x z




array([[ 64,  90, 142],
       [ 51,  69,  91],
       [ 41,  67,  87]])

In [19]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


/usr/local/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


In [20]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


Addition of a scalar (100)
-------------------------
 [[106 108 108]
 [105 103 107]
 [107 105 102]]


In [7]:
print("\nExponentiation, matrix CUBE here\n----------------------------------------\n", mat1**3)


Exponentiation, matrix CUBE here
----------------------------------------
 [[  8   1  27]
 [729 125 125]
 [343   8 216]]


In [6]:
print("\nExponentiation, SQUARE Root using pow() function\n-------------------------------------------\n",pow(mat1,0.5))


Exponentiation, SQUARE Root using pow() function
-------------------------------------------
 [[1.41421356 1.         1.73205081]
 [3.         2.23606798 2.23606798]
 [2.64575131 1.41421356 2.44948974]]


### Broadcasting

Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.
The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. 

NumPy operations are usually done on pairs of arrays on an element-by-element basis. 

In the simplest case, the two arrays must have exactly the same shape.

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
When operating on two arrays, NumPy compares their shapes element-wise. 

It starts with the trailing dimensions, and works its way forward. 

Two dimensions are compatible when they are equal, or one of them is 1.

In [18]:
#adds 100 to each element of array
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [19]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0,3,5])
print(add_rows)

# add to each row of 'start' using broadcasting- added row wise
y = start + add_rows 
print(y)

[1 0 3 5]
[[101. 100. 103. 105.]
 [101. 100. 103. 105.]
 [101. 100. 103. 105.]
 [101. 100. 103. 105.]]


In [24]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)


# add to each column of 'start' using broadcasting - added column wise
y = start + add_cols 
print(y)

# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[0]
 [1]
 [2]
 [3]]
[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]
[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


### Array Math

covers - addition, modulus, exponentiation, sqrt, log, etc

np.sqrt()
np.exp()
np.log10()

In [25]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[3 3 5]
 [3 8 9]
 [5 8 5]]

2nd Matrix of random single-digit numbers
------------
 [[1 7 8]
 [3 6 4]
 [7 4 1]]


In [31]:
print("\nSquare-root of 1st matrix using np.sqrt() \n------------------\n", np.sqrt(mat1))


Square-root of 1st matrix using np.sqrt() 
------------------
 [[1.73205081 1.73205081 2.23606798]
 [1.73205081 2.82842712 3.        ]
 [2.23606798 2.82842712 2.23606798]]


In [32]:
print("\nExponential power of 1st matrix using np.exp() \n",'-'*50,"\n", np.exp(mat1))


Exponential power of 1st matrix using np.exp() 
 -------------------------------------------------- 
 [[  20.08553692   20.08553692  148.4131591 ]
 [  20.08553692 2980.95798704 8103.08392758]
 [ 148.4131591  2980.95798704  148.4131591 ]]


In [33]:
print("\n10-base logarithm on 1st matrix using np.log10()\n",'-'*50,"\n", np.log10(mat1))


10-base logarithm on 1st matrix using np.log10()
 -------------------------------------------------- 
 [[0.47712125 0.47712125 0.69897   ]
 [0.47712125 0.90308999 0.95424251]
 [0.69897    0.90308999 0.69897   ]]


In [34]:
print("\nModulo reminder using np.fmod()  \n",'-'*50,"\n", np.fmod(mat1,mat2))
print("\nAnother way of getting Modulo reminder using Mat1%Mat2 \n",'-'*50,"\n", mat1%mat2)



Modulo reminder using np.fmod()  
 -------------------------------------------------- 
 [[0 3 5]
 [0 2 1]
 [5 0 0]]

Another way of getting Modulo reminder using Mat1%Mat2 
 -------------------------------------------------- 
 [[0 3 5]
 [0 2 1]
 [5 0 0]]


In [35]:
print("\nCombination of functions by showing exponential decay of a sine wave\n",'-'*70)
A = np.linspace(0,12*np.pi,1001)
A


Combination of functions by showing exponential decay of a sine wave
 ----------------------------------------------------------------------


array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])